### ISSUE TITLE
using a real defconfig instead of .config

### ISSUE THREAD

**Issue by r043v** [wolfallein/clokworkpi-kernel#1]
hi and thanks for your work :)

distribute a defconfig file instead of a raw .config could be way better,
defconfig file is a .config file stripped from all kernel default value,
that's mean if next kernel release change default value they where directly reflected into our config file without manual intervention & without distribute overwrited old conf flag
also the file will be more lighter to read (for example your one ~3900 lines, my arch defconfig have 246 lines)

kernel make script can generate a defconfig file from a .config using make savedefconfig

it must be copied into arch/arm/configs/ like you already put, in my port i name it gameshell_defconfig,
in second step, before the build process you have to call make gameshell_defconfig to generate a full .config file from the defconfig file, without any cp

**Comment by wolfallein** [comment]
Thank you,

I didn't know how to create my defconfig. I'll update it.

**Comment by wolfallein** [comment]
updated in last commit

**Comment by r043v** [comment]
thanks !!
i made a diff from our twice, it must help us remove unnecessary things & optimize a bit :)

> [gs@gs linux-gameshell]$ src/linux-5.5.2/scripts/diffconfig ./clockworkpi_cpi3_defconfig ./defconfig 
> -BT_HCIUART_H4 y
> -CRYPTO_CCM y
> -CRYPTO_GCM y
> -DEBUG_KERNEL y
> -HID_A4TECH n
> -HID_APPLE n
> -HID_BELKIN n
> -HID_CHERRY n
> -HID_CHICONY n
> -HID_CYPRESS n
> -HID_EZKEY n
> -HID_ITE n
> -HID_KENSINGTON n
> -HID_LOGITECH n
> -HID_MICROSOFT n
> -HID_MONTEREY n
> -LOGO y
> -LOGO_LINUX_MONO n
> -LOGO_LINUX_VGA16 n
> -NR_CPUS 8
> -XZ_DEC y
>  BRCMFMAC y -> m
>  DEFAULT_HOSTNAME "clockworkpi " -> "gs"
>  LOCALVERSION "-clockworkpi-cpi3" -> "-gs"
> +ATA y
> +AUTOFS4_FS y
> +B43 m
> +B43LEGACY m
> +B43LEGACY_DEBUG n
> +B43_SDIO y
> +BACKLIGHT_GPIO y
> +BCMA y
> +BINFMT_MISC y
> +BLK_DEV_INITRD y
> +BRCMFMAC_USB y
> +BT_BNEP y
> +BT_HCIUART_3WIRE y
> +BT_HCIUART_BCM y
> +BUILD_SALT "mk"
> +CFG80211_DEFAULT_PS n
> +CORDIC y
> +CPU_FREQ_DEFAULT_GOV_SCHEDUTIL y
> +CPU_FREQ_GOV_CONSERVATIVE y
> +CRYPTO_ARC4 y
> +CRYPTO_USER y
> +CRYPTO_USER_API_AEAD y
> +CRYPTO_USER_API_HASH y
> +CRYPTO_USER_API_RNG y
> +CRYPTO_USER_API_SKCIPHER y
> +CUSE y
> +DEBUG_BUGVERBOSE n
> +DRM_DUMB_VGA_DAC y
> +DRM_SUN4I_HDMI_CEC y
> +DRM_SUN8I_DW_HDMI y
> +DRM_VKMS y
> +EMBEDDED y
> +EXT4_FS_POSIX_ACL y
> +FONTS y
> +FONT_8x8 y
> +FRAMEBUFFER_CONSOLE y
> +FUSE_FS y
> +INPUT_UINPUT y
> +KERNEL_LZ4 y
> +MAC80211 y
> +MODULE_UNLOAD y
> +MUSB_PIO_ONLY y
> +NAMESPACES y
> +PCI y
> +PKCS8_PRIVATE_KEY_PARSER y
> +POSIX_MQUEUE y
> +SERIAL_DEV_BUS y
> +SIGNED_PE_FILE_VERIFICATION y
> +SND_SUN4I_CODEC y
> +SND_SUN4I_SPDIF y
> +SSB y
> +SYSVIPC y
> +USB_ANNOUNCE_NEW_DEVICES y
> +USB_ULPI y
>

**Comment by wolfallein** [comment]
Thanks! At some point, we could merge our changes and create one standard version. Do the official developers still working on software development, or they just want to sell more devices? Do you work for them? Looks like only the community is trying to fix things, update, making more templates. Debian buster is broke, and it was released almost one year ago. After the CPI launch looks like everything stopped there, and we got very small changes.

**Comment by r043v** [comment]
> At some point, we could merge our changes and create one standard version.

will be great, that's the way to go, community currently start scatter a bit %)

> Do you work for them?

off course not, else some of my projects may have be mainlined ^^

> Do the official developers still working on software development, or they just want to sell more devices?

that's the point, minimal work, in fact each software release was done in a hurry after some community pressure .. :- /

on hardware it's the same, as the gs is make to be modular and they never (and will ever ?) release compatible module, in fact the modular philosophy is now a defect instead of a great thing

from the start community tried to make advance but clockwork doesn't really make real cooperation and work alone

by example, os 0.3 was released because all the forum rant for lima support (in fact lima was broken)
first kernel 5.x was from [community](https://forum.clockworkpi.com/t/clockworkpi-emulated-system/3539), os 0.4 with a new kernel was released a few month later (lima still broken) ..
and 0.5 was released one week after arch port release ..

duckyvirus tried to recreate from scratch a new debian image but stopped as the lack of info and support, finally some great guys leaved the community

we stopped count about launcher who brick the handled and force us about reflashing ...

i tried make real advance as i could, like the first compo where i made a [dedicated apt client](https://forum.clockworkpi.com/t/gameshell-ecosystem/3209) with an associated server, not any mainline integration or any official comments (and also not any submission yet from the community) ..
so it's funny on my eyes to see warehouse coming one year later xD

as guu said us it's not him who made the kernel i think kernel part was external, subcontracted ?
maybe [steward-fu](https://steward-fu.github.io/website/handheld.htm) ?

also i could have a few words around compo results, strange decision who make won really bad entries, not any judge comments and notation, splitting the community in two part (world vs china) on compo #3 with giving 20 gameshell to chinese teams and make an irl party in pekin ... so i just stopped participate after the first :- )

finally, at the end i made what i think was a need, full separation with new os & launcher.

lol i seem a bad painting but it's a good platform, also guu done a good job, made things advance as it can (and he answer pm messages :)

**Comment by wolfallein** [comment]
Thanks for the words. I bought the gameshell one year ago for some projects that I have. The broke SO made me not very interested in the beginning, and it was in a box for all this time.

Gameshell is practically the only SBC that has power management that can run with batteries, and the modularity of it can lead to very interesting projects. Most SBC on the market don't have any power management and the ones that have it, are somehow broken.

If we think about gaming, the gameshell is not the best option. The LCD is one of the worst that I have seen (I tried to play some games but give up because of the screen), the buttons often get stuck, the battery is ridiculously small (and we have space for a bigger one). I think there are better things for a lower price (have you seen the odroid go advance: https://www.hardkernel.com/shop/odroid-go-advance/ ), especially if we include the import tax. I could have bought a Nintendo Switch Lite for what I spent (tax + device).

Seems like clockwork staff is trying to push it hard as a game console, and the game jam as you mentioned is a bit dubious. For the last, they had just a few developers from outside the community (I think) and they even said: 

> We think we should set the bar high and keep the standard at the same level as our previous jams. 

What is the incentive for better games? Why they don't hire game developers if they want better things? 

Why the community alone needs to develop their kernel, their SO, and games for them?

In my opinion, the gameshell is an SBC with a lot of potentials, and can also be a gaming device, not the opposite. Any smartphone nowadays can emulate better and have better games available.

The software should be the priority. A good platform will attract people. Raspberry is what it is because of the continuous software development, and the community. The hardware was very bad on earlier models, but they and the community managed to make it ran a lot of things that Rpi simply didn't have enough power.

I was thinking to also create a Debian port from scratch, but what you said is making me think twice. Their image has a lot of things that you don't have an idea from where it came, or what they changed. The documentation is inexistent.

Anyway, I'm just a bit frustrated with the software side, and lack of official communication.

**Comment by r043v** [comment]
you're rigth at all the points,
modular keypad made buttons unresponsive, also as they are grouped at the same place so we don't have L & R and lightkey is just a joke ..
batterie is pretty small, and doesn't ave great live, as i dev onto there is some times i got the usb wire plugged, now the bat life time is under one hour ... Oo
i don't have trouble with screen, anyway it is pretty small ... back us to the gp32 times with 320x240 ..

(also don't have an usb port is a real problem, like others things like volume whell ect ... 

i never check about the power management point on soc, you're right it's mostly rare

i also get a pocketchip, yet the keyboard sucks but screen is great and modular is finally also here .. maybe the gs would have got the same way, dedicated motherboard with screen & pad with a pluggable soc .. like a pi ?

also yes gs is pretty expensive, really really too much .. when as you link we see the advance there is no comparison, hardkernel got some experience from long time, pretty serious, i'll buy one for sure

as clockwork is tiny i could understand they cannot really made software as we would really want to see,
but the real trouble is they not listen and take in account what we want and what we done, they just do as we not exist, ersaing our advance by releasing a new (empty) os, they wanna want keep the hands on

not just the 3rd compo where dubious, it was started as the first
https://itch.io/jam/gameshell/entries
https://forum.clockworkpi.com/t/announcing-the-1st-clockwork-game-jam-event/1943/40
just try GYATM and make your own judgment ;)

> What is the incentive for better games? Why they don't hire game developers if they want better things?

yes and no, back in times (gp32/gba era) compo where get 50+ entries, here they promise 10+ units for the winner and they only get few entries with some been pico8 ones
have real exclusivity is not the point here, but have they're full time dev like guu could port great stuff like gzdoom by example, i join you for this, all the work is done by the community on their spare time and clockwork don't do any effort on make "mainline" all this work

> I was thinking to also create a Debian port from scratch, but what you said is making me think twice.

just do it, the only unknow is the point you have reveled with the lima breaked/lib downgrade !

> Anyway, I'm just a bit frustrated with the software side, and lack of official communication.

and you're right to be ! honestly the soft doesn't really made the hard really usable..

real trouble is launcher, can crash easily, selected things is a pain and have launcher must be relauched at every program close just suck, i made advance on this point with real multitask but as usual they do like we not exist.
